services:
  autopulse:
    image: danonline/autopulse
    container_name: autopulse
    restart: always
    depends_on:
      postgres:
         condition: service_healthy
    ports:
      - 2875:2875
    networks:
      - db
    volumes:
      - ./config.yaml:/app/config.yaml
      - /etc/localtime:/etc/localtime:ro # for correct timezone in timestamps
    environment:
       AUTOPULSE__APP__DATABASE_URL: postgres://autopulse:autopulse@postgres/autopulse

  # Optional self-hosted UI
  # ui:
  #   image: danonline/autopulse:ui
  #   container_name: autopulse-ui
  #   restart: always
  #   ports:
  #     - 2880:2880
  #   environment:
  #     # SECRET: your_secret_here # Optional to prevent being logged out when the container restarts
  #   # networks: # If you want to use an internal autopulse network, ex. http://autopulse:2875
  #   #   - db

  postgres:
    image: postgres:alpine
    container_name: autopulse-postgres
    restart: always
    networks:
      - db
    environment:
      POSTGRES_USER: autopulse
      POSTGRES_PASSWORD: autopulse
      POSTGRES_DB: autopulse
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db:/var/lib/postgresql/data
  
networks:
  db:
    driver: bridge