[app]
hostname = "0.0.0.0"
port = 2875
database_url = "postgres://autopulse:autopulse@localhost:5432/autopulse"
log_level = "info"

[auth]
username = "admin"
password = "password"

[opts]
check_path = true
max_retries = 5

[triggers.manual]
type = "manual"

[targets]

[webhooks]
