name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  server:
    name: Server Build and Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: ./.github/actions/setup-nix
        with:
          cache-name: checks
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, format, lint, and test
        run: nix flake check --no-update-lock-file --print-build-logs
