name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  server:
    name: Server Build and Check
    runs-on: ubuntu-latest
    env:
      SCCACHE_GHA_ENABLED: "true"
    steps:
      - name: Checkout Project
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.10

      - uses: rrbutani/use-nix-shell-action@v1

      - name: Cargo Cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          restore-keys: |
            ${{ runner.os }}-cargo-release-x86_64-unknown-linux-musl-
          key: ${{ runner.os }}-cargo-release-x86_64-unknown-linux-musl-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release

      - name: Format Check
        run: cargo fmt -- --check

      - name: Clippy Check
        run: cargo clippy --release --workspace -- -D warnings

      - name: Test
        run: cargo nextest run --release --workspace