name: Docs
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout Project
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: ./.github/actions/setup-nix
        with:
          cache-name: docs
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docs
        run: |
          nix build --no-update-lock-file --print-build-logs .#docs
          cp -rL result/share/doc site

      - name: Publish to Cloudflare Pages
        uses: dan-online/pages-action@main
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: autopulse
          directory: site
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          productionBranch: main
